config/routes.rb
Rails.application.routes.draw do
  root 'root#index'
  resources :gossips
  resources :comments

  resources :sessions, only: [:new, :create, :destroy]

  
  resources :users, only: [:show, :new, :create]
  resources :welcome, only: [:index]
  
  resources :contact, only: [:index]
  resources :team, only: [:index]
  resources :root, only: [:index]
  resources :city, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates :zip_code,
    presence: true,
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
    validates :name, presence: true
    
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
 
  belongs_to :user
  belongs_to :gossip
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, length: { in: 3..14 }
  validates :content, presence: true
  
  belongs_to :user
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips
  has_many :comments
  has_many :likes
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  belongs_to :comment
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  validates :content, presence: true
  
  belongs_to :recipient, class_name: "User"
  belongs_to :sender, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true
  
  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  validates :email,
  presence: true,
  uniqueness: true,
  format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :first_name, presence: true 
  validates :last_name, presence: true

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments
  has_many :likes
  has_secure_password

  def to_session
    {id: @user.id}
  end
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def show
  end
  
def user
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new(gossip: "Gossip", user: User.last, content: "Contenu")
  end

  # Create a new comment
  def create
    gossip = Gossip.find(params[:gossip])

    comment = Comment.new(gossip: gossip,
                          user: User.last,
                          content: params[:content])

    if comment.save
      flash[:success] = "Le potin a été créé avec succès."
      redirect_to gossip_path(id: Gossip.find(gossip.id))
    else
      redirect_to gossip_path(id: Gossip.find(gossip.id))
    end
  end
  
  def show
    @comment = Comment.find(params[:id])
  end

	def index
		@comment = Comment.all
	end


def update
	@comment = Comment.find(params[:id])
	if @comment.update(comment_params)
		flash[:success] = "Ton super potin a correctement été mis à jour !"
		redirect_to gossips_path(@comment.gossip.id)
	else
		render 'edit'
	end
end

	def edit
		@comment = Comment.find(params[:id])
	end

	

def destroy
	@comment = Comment.find(params[:id])
	if @comment.destroy
		redirect_to gossips_path(@comment.gossip.id)
	else 
		render 'edit'
	end
end

end

private
	
def comment_params
  params.require(:comment).permit(:content, :gossip)
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

def index
end

def contact
end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

	def new
		@gossip = Gossip.new
	end

	def create
    @gossip = Gossip.new(user: User.first, title: params[:title], content: params[:content])
    #title: params[:title], content: params[:content], user: params[:user] # avec xxx qui sont les données obtenues à partir du formulaire

	if @gossip.save # essaie de sauvegarder en base @gossip
    redirect_to gossips_path
  else
   render 'new' # sinon, il render la view new (qui est celle sur laquelle on est déjà)
  end
	end

	def show
		@gossip = Gossip.find(params[:id])
	end

	def index
		@gossip = Gossip.all
	end


def update
	@gossip = Gossip.find(params[:id])
	if @gossip.update(gossip_params)
		flash[:success] = "Ton super potin a correctement été mis à jour !"
		redirect_to gossips_path
	else
		render :edit
	end
end

	def edit
		@gossip = Gossip.find(params[:id])
	end

	

def destroy
	@gossip = Gossip.find(params[:id])
	if @gossip.destroy
		redirect_to gossips_path
	else 
		render 'destroy'
	end
end

end

private
	
def gossip_params
  params.require(:gossip).permit(:title, :content)
end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def index
  end
  

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team 
  end

  def contact
  end

  def gossip
  end

  def welcome
      @user = params[:id]
  end

  def index
      @gossip = Gossip.all
  end 

  def show
    @gossip = Gossip.find(params[:id])
  end 

  def user
  end 

end 

app/controllers/team_controller.rb
class TeamController < ApplicationController

def index
end

def team 
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

def create
  
    @user = User.new( 'first_name' => params[:first_name],
                      'last_name' => params[:last_name],
                      'age' => params[:age],
                      #'city_id' => City.all.sample.id , 
                      'email' => params[:email],
                      'password' => params[:password]
                      )
                    
      if @user.save # essaie de sauvegarder en base @user
        flash.notice = "User successfully created"
        redirect_to gossips_path
      else
        flash.alert = "User can not be registred"
        redirect_to new_user_path
        flash.alert = nil
      end
    
end

  def new
      @user = User.new
  end

#def user_params
 # params.require(:user).permit(:email, :age, :password, :first_name, :last_name, :city_id)
#end

end


	

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

def welcome
  @user = params[:id]
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/city/show.html.erb
<html>
<head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=root_path%>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    
      <a class="nav-item nav-link active" href="<%=gossips_path %>">Liste des potins <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=new_gossip_path %>">Créer un potin <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=team_index_path %>">Team <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=contact_index_path %>">Contact <span class="sr-only">(current)</span></a>  
      <a class="nav-item nav-link active" href="<%=new_user_path %>">Créer un compte <span class="sr-only">(current)</span></a> 
      <a class="nav-item nav-link active" href="<%=new_session_path %>">Se connecter <span class="sr-only">(current)</span></a>   
    </div>
  </div>
</nav>
</head>

<body>
    <div class="container py-5 text-center">
      <% city = City.find(params['id']) %>
      <h3 class="pb-3">Tous les gossips de <%= city.name %>  !</h3>
      <br/>

      <div class="card-deck row justify-content-center">
        <% city.users.each do |user| %>
          <% user.gossips.each do |gossip| %>
            <div class="col-lg-8 col-md-12 mb-3">
              <div class="card text-left">
                <div class="card-body">
                  <h5 class="card-title">
                    <%= link_to "#{gossip.title}", gossip_path(gossip.id) %>
                  </h5>
                  <p class="card-text"><%= gossip.content %></p>
                </div>
                <div class="card-footer">
                  <p class="small text-right text-muted">de <%= link_to "#{gossip.user.first_name}", user_path(gossip.user.id) %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

    </div>
</body>
    
</html>

app/views/gossips/edit.html.erb
<!doctype html>

<html>
<head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=root_path%>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    
      <a class="nav-item nav-link active" href="<%=gossips_path %>">Liste des potins <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=new_gossip_path %>">Créer un potin <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=team_index_path %>">Team <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=contact_index_path %>">Contact <span class="sr-only">(current)</span></a>  
      <a class="nav-item nav-link active" href="<%=new_user_path %>">Créer un compte <span class="sr-only">(current)</span></a> 
      <a class="nav-item nav-link active" href="<%=new_session_path %>">Se connecter <span class="sr-only">(current)</span></a>   
    </div>
  </div>
</nav>
</head>
  
 <body>

   
 <%= form_for @gossip do |f| %>

 <div classs = "form-group">

     <label> Titre</label>
     <%= f.text_field :title, class: 'form-control' %>
  </div>
     
<div class = 'form-group'>

  <label> Contenu</label>
     <%= f.text_area :content, class: 'form-control' %>
    </div>

<div class = 'form-group'>
    <%= f.text_field :user, class: 'form-control' %>
</div>
    <br /> <br />
<div class = 'form-group'>
   <button type="submit"> Editer</button> 

</div>


    <% end %>

      
  </body>
</html>

app/views/gossips/index.html.erb
<html>
<head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=root_path%>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    
      <a class="nav-item nav-link active" href="<%=gossips_path %>">Liste des potins <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=new_gossip_path %>">Créer un potin <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=team_index_path %>">Team <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=contact_index_path %>">Contact <span class="sr-only">(current)</span></a>  
      <a class="nav-item nav-link active" href="<%=new_user_path %>">Créer un compte <span class="sr-only">(current)</span></a> 
      <a class="nav-item nav-link active" href="<%=new_session_path %>">Se connecter <span class="sr-only">(current)</span></a>   
    </div>
  </div>
</nav>
</head>

<body>

<% if params[:commit] == "Envoyer" %>
     <p class="container alert alert-success d-flex justify-content-center" role="alert">Ton potin a été enregistré !</p>
  <% end %>

<div class="container py-3 text-center">
  <a class= text-center><h1>Liste des potins </h1></a>

</div>


<div class="row justify-content-center">
  <div class="col-lg-4 col-md-6 mb-3">
    <div class="card">
    <% @gossip.each do |gossip| %>
      <div class="card-body"> 
        <h5 class="card-title"><%= gossip.user.first_name %></h5>
        <p class="card-text">titre : <%= gossip.title %></p>
  <button type="button" class="btn btn-outline-primary"><%= link_to "Voir le potin", gossip_path(gossip.id) %></button>
      </div>
      <% end %>
    </div>
    
  </div>


</body>




</html>

app/views/gossips/new.html.erb
<html>

<head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=root_path%>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    
      <a class="nav-item nav-link active" href="<%=gossips_path %>">Liste des potins <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=new_gossip_path %>">Créer un potin <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=team_index_path %>">Team <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=contact_index_path %>">Contact <span class="sr-only">(current)</span></a>  
      <a class="nav-item nav-link active" href="<%=new_user_path %>">Créer un compte <span class="sr-only">(current)</span></a> 
      <a class="nav-item nav-link active" href="<%=new_session_path %>">Se connecter <span class="sr-only">(current)</span></a>   
    </div>
  </div>
</nav>
</head>
  <body>


<% if @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
       
<% end %>
<% end %>
  </div>
  
 <div class="container text-center mt-5">
      <h1 style="color: #053557">Créer ton potin &#128520;</h1>
      <div class="m-5 px-5">
        <%= form_tag url_for(action: 'create'), method: "post" do %>


          <div class="form-group">
          <%= text_field_tag 'title', @gossip.title, class: 'form-control', placeholder: 'Titre' %>
          </div> 

          <div class="form-group">
          <%= text_area_tag 'content', @gossip.content, class: 'form-control', placeholder: 'Contenu' %>
          </div> 

          <div class="btn-toolbar mx-3" role="toolbar" aria-label="Toolbar with button groups">
    
            <div class="btn-group mr-2" role="group">
              <%= submit_tag "Créer", class: "btn btn-primary mx-1" %> 
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <!-- ... -->
  </body>
</html>

app/views/gossips/show.html.erb
<!doctype html>

<html>
<head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=root_path%>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    
      <a class="nav-item nav-link active" href="<%=gossips_path %>">Liste des potins <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=new_gossip_path %>">Créer un potin <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=team_index_path %>">Team <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=contact_index_path %>">Contact <span class="sr-only">(current)</span></a>  
      <a class="nav-item nav-link active" href="<%=new_user_path %>">Créer un compte <span class="sr-only">(current)</span></a> 
      <a class="nav-item nav-link active" href="<%=new_session_path %>">Se connecter <span class="sr-only">(current)</span></a>   
    </div>
  </div>
</nav>
</head>
  
 <body>
 <br>

    <h2>Voici la page du potin n°<%= params['id']%> </h2>
    <p> Le contenu du potin : <%= @gossip.content%> </p>
    <p> L'auteur du potin : <%= @gossip.user.first_name %> 
    <br>
    <br>
    
    
    <i><%= link_to "--> En savoir plus sur l'auteur", user_path(@gossip.user.id) %></i></p>
    <i><%= link_to "--> En savoir plus sur la ville", city_path(@gossip.user.city.id) %>, <%= @gossip.user.city.name %></i></p> 
  
    <br> 
    <a href="<%= edit_gossip_path(@gossip.id) %>" class="btn btn-warning text-white mx-1">Modifier le potin</a>
    
    <a href="<%= gossip_path(@gossip.id) %>" class="btn btn-danger mx-1" data-confirm="Êtes-vous sûrs de vouloir le supprimer ?" data-method="DELETE">Supprimer le potin</a>

<br>
<br>

      <%= form_tag comment_path(gossip: @gossip), method: "post" do %>
          <div class="form-group">
            <%= label_tag 'Ajouter un commentaire :' %>
            <%= text_area_tag 'content', @comment, {class: 'form-control', rows: 5, placeholder: "Saisissez votre commentaire..."} %>
          </div>
          <div class="row justify-content-center">
            <%= submit_tag "Valider", {class: 'btn btn-primary'} %>
          </div>
        <% end %>

  </body>
  </body>
</html>

app/views/users/new.html.erb
<html>
<head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=root_path%>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    
    <a class="nav-item nav-link active" href="<%=gossips_path %>">Liste des potins <span class="sr-only">(current)</span></a>
    <a class="nav-item nav-link active" href="<%=new_gossip_path %>">Créer un potin <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=team_index_path %>">Team <span class="sr-only">(current)</span></a>
<a class="nav-item nav-link active" href="<%=contact_index_path %>">Contact <span class="sr-only">(current)</span></a>     
    </div>
  </div>
</nav>
</head>

<body>
   <div class="panel panel-default">
    <div class="panel-heading text-center"> S'inscrire</div>
      <div class="panel-body row justify-content-center">
        <%= form_for @user, class:'form-horizontal' do |f|%>
          
          <div class="form-group">
            <%= f.label :last_name, "Nom", class: 'col-md-4 control-label' %>
              <div class="col-md-6">
                <%= f.text_field :last_name, class: 'form-control' %>
              </div>
          </div>


          <div class="form-group">
            <%= f.label :first_name, "Prénom", class: 'col-md-4 control-label' %>
              <div class="col-md-6">
                <%= f.text_field :first_name, class: 'form-control' %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :email, "Email", class: 'col-md-4 control-label' %>
              <div class="col-md-6">
                <%= f.email_field :email, class: 'form-control' %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :city, "Ville", class: 'col-md-4 control-label' %>
              <div class="col-md-6">
                <%= f.text_field :city, class: 'form-control' %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :password, "Password", class: 'col-md-4 control-label' %>
              <div class="col-md-6">
                <%= f.password_field :password, class: 'form-control' %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, "Confirmer password", class: 'col-md-4 control-label' %>
              <div class="col-md-6">
                <%= f.password_field :password_confirmation, class: 'form-control' %>
              </div>
          </div>


<div class="form-group">
  <div class="col-md-6 col-md-offset-4">
    <button type="submit" class="btn btn-primary"> 
      S'inscrire 
    </button>
  </div>
</div>
       

        <% end %>
      </div>
  </div>  
      
  </body>
    
</html>

app/views/users/show.html.erb
<html>
<head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=root_path%>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    
      <a class="nav-item nav-link active" href="<%=gossips_path %>">Liste des potins <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=new_gossip_path %>">Créer un potin <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=team_index_path %>">Team <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="<%=contact_index_path %>">Contact <span class="sr-only">(current)</span></a>  
      <a class="nav-item nav-link active" href="<%=new_user_path %>">Créer un compte <span class="sr-only">(current)</span></a> 
      <a class="nav-item nav-link active" href="<%=new_session_path %>">Se connecter <span class="sr-only">(current)</span></a>   
    </div>
  </div>
</nav>
</head>

<body>
    <% user = User.find(params['id']) %>


<div class="row justify-content-center">
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="https://pixabay.com/get/52e4dc4b4e57ab14f6da8c7dda35367b1d37d6e35755754b_1280.png" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title text-center">Infos utilisateurs</h5>
<p class="card-text text-center"><%= user.first_name%> <%= user.last_name%></p>  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item text-center"><%= user.email%></li>
    <li class="list-group-item"><%= user.description%></li>
    <li class="list-group-item text-center"><%= user.age%></li>


    <li class="list-group-item text-center"> <%= user.city.name%> <br/>
    <%= link_to "Infos sur la ville", city_path(user.city.id) %>
    </li>

</div>
</div> 
      
  </body>
    
</html>